spring:
  datasource:
    url: jdbc:postgresql://postgres:6GuIqjmJokMUxABiuIRk@containers-us-west-46.railway.app:6883/railway
    username: postgres
    password: 6GuIqjmJokMUxABiuIRk
    name: share-management-api

  sql:
    init:
      mode: always # you won't do this in prod, I'm just doing this for demo purposes