spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/sharemanagement?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    username: shareuser
    password: Amen@2461
  sql:
    init:
      mode: always
  jpa:
    # Hibernate is an ORM (Object Relational Mapper)
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
#        logging:
#          level:
#            org:
#              springframework=DEBUG:
