spring:
  datasource:
    url: jdbc:postgresql://containers-us-west-46.railway.app:6883/share_db
    username: postgres
    password: 6GuIqjmJokMUxABiuIRk
    name: share-api

  sql:
    init:
      mode: always # you won't do this in prod, I'm just doing this for demo purposes